import fs from "fs";

const BEUI_ITEMS = [
  // --- Motion Components ---
  {
    id: "beui-arc-picker",
    name: "Arc Picker Radial Dial",
    nameCn: "弧形圆环角度与档位旋转拾取器",
    category: "component",
    siteId: "beui",
    siteName: "beui.dev",
    siteUrl: "https://beui.dev",
    originUrl: "https://beui.dev/components/motion/arc-picker",
    status: "collected",
    description: "具有自然角度惯性阻尼的圆弧交互转盘，用于温度、音量或多档位精密选择。",
    tags: ["ArcPicker", "Radial", "Motion"],
    componentKey: "beui-arc-picker-demo",
  },
  {
    id: "beui-sortable-stack",
    name: "Sortable Stack Drag Reorder",
    nameCn: "卡片堆叠拖拽与动态重排序",
    category: "component",
    siteId: "beui",
    siteName: "beui.dev",
    siteUrl: "https://beui.dev",
    originUrl: "https://beui.dev/components/motion/sortable-stack",
    status: "collected",
    description: "类似物理卡牌抽出的堆叠动画，支持上下滑动切换焦点与层级穿透。",
    tags: ["Sortable", "Stack", "Cards"],
    componentKey: "beui-sortable-stack-demo",
  },
  {
    id: "beui-color-selector",
    name: "Animated Color Selector Swatches",
    nameCn: "动态调色板展开与色块脉冲选择器",
    category: "component",
    siteId: "beui",
    siteName: "beui.dev",
    siteUrl: "https://beui.dev",
    originUrl: "https://beui.dev/components/motion/color-selector",
    status: "collected",
    description: "点击色环扇形放射展开全部主题色，选中色块伴随流体波纹形变效果。",
    tags: ["ColorPicker", "Palette", "Motion"],
    componentKey: "beui-color-selector-demo",
  },
  {
    id: "beui-tilt-card",
    name: "Tilt Card 3D Perspective Hover",
    nameCn: "3D 视差倾斜与深度光影悬浮卡片",
    category: "component",
    siteId: "beui",
    siteName: "beui.dev",
    siteUrl: "https://beui.dev",
    originUrl: "https://beui.dev/components/motion/tilt-card",
    status: "collected",
    description: "高灵敏度响应光标相对坐标，实时计算 pitch/roll 旋转并投射高光反光层。",
    tags: ["Tilt", "3D", "Card"],
    componentKey: "beui-tilt-card-demo",
  },
  {
    id: "beui-expanding-arrow-button",
    name: "Expanding Arrow CTA Button",
    nameCn: "箭头位移展开与弹性微动效主按钮",
    category: "component",
    siteId: "beui",
    siteName: "beui.dev",
    siteUrl: "https://beui.dev",
    originUrl: "https://beui.dev/components/motion/expanding-arrow-button",
    status: "collected",
    description: "悬停时图标右滑破界而出并带动容器胶囊宽度平滑延展，极具点击驱动力。",
    tags: ["Button", "Arrow", "CTA"],
    componentKey: "beui-arrow-button-demo",
  },
  {
    id: "beui-adaptive-stepper",
    name: "Adaptive Stepper Number Control",
    nameCn: "自适应手势滑动步进器",
    category: "component",
    siteId: "beui",
    siteName: "beui.dev",
    siteUrl: "https://beui.dev",
    originUrl: "https://beui.dev/components/motion/adaptive-stepper",
    status: "collected",
    description: "支持左右拖拽手势快速调值与长按连续加速，数字平滑翻牌过渡。",
    tags: ["Stepper", "Control", "Input"],
    componentKey: "beui-adaptive-stepper-demo",
  },
  {
    id: "beui-wheel-picker",
    name: "Wheel Picker Inertial Scroll",
    nameCn: "仿 iOS 滚轮式时间与参数滚动选择器",
    category: "component",
    siteId: "beui",
    siteName: "beui.dev",
    siteUrl: "https://beui.dev",
    originUrl: "https://beui.dev/components/motion/wheel-picker",
    status: "collected",
    description: "仿机械滚轮透视滚动，中央聚光区域自动对齐刻度并产生触感反馈。",
    tags: ["Wheel", "Picker", "Date"],
    componentKey: "beui-wheel-picker-demo",
  },
  {
    id: "beui-animated-toast-stack",
    name: "Animated Toast Stack Queue",
    nameCn: "堆叠层叠通知卡片流",
    category: "component",
    siteId: "beui",
    siteName: "beui.dev",
    siteUrl: "https://beui.dev",
    originUrl: "https://beui.dev/components/motion/animated-toast-stack",
    status: "collected",
    description: "后置通知自动按阶梯缩小并带有半透明景深感，点击悬停时展开列表。",
    tags: ["Toast", "Notification", "Motion"],
    componentKey: "beui-toast-stack-demo",
  },
  {
    id: "beui-action-swap",
    name: "Action Swap State Morph",
    nameCn: "双态操作互换与形变动效按钮",
    category: "component",
    siteId: "beui",
    siteName: "beui.dev",
    siteUrl: "https://beui.dev",
    originUrl: "https://beui.dev/components/motion/action-swap",
    status: "collected",
    description: "从“下载”平滑形变为“进度环”再形变为“打开文件”，全流程一体化无刷新。",
    tags: ["ActionSwap", "Morph", "Button"],
    componentKey: "beui-action-swap-demo",
  },

  // --- Blocks Components ---
  {
    id: "beui-dynamic-island",
    name: "Dynamic Island Capsule Header",
    nameCn: "灵动岛多模态交互胶囊浮窗",
    category: "block",
    siteId: "beui",
    siteName: "beui.dev",
    siteUrl: "https://beui.dev",
    originUrl: "https://beui.dev/components/blocks/dynamic-island",
    status: "collected",
    description: "支持在通话、音乐播放、计时器与系统告警间无缝拉伸与形态突变。",
    tags: ["DynamicIsland", "Capsule", "Header"],
    componentKey: "beui-dynamic-island-demo",
  },
  {
    id: "beui-command-palette",
    name: "Command Palette Fuzzy Quick Launcher",
    nameCn: "沉浸式全局指令检索中心",
    category: "block",
    siteId: "beui",
    siteName: "beui.dev",
    siteUrl: "https://beui.dev",
    originUrl: "https://beui.dev/components/blocks/command-palette",
    status: "collected",
    description: "带分组图标、键盘热键绑定与最近操作记录的快捷呼出面板。",
    tags: ["Command", "Palette", "Search"],
    componentKey: "beui-command-palette-demo",
  },
  {
    id: "beui-morphing-search",
    name: "Morphing Search Expandable Bar",
    nameCn: "从图标形变展开的流式搜索条",
    category: "block",
    siteId: "beui",
    siteName: "beui.dev",
    siteUrl: "https://beui.dev",
    originUrl: "https://beui.dev/components/blocks/morphing-search",
    status: "collected",
    description: "静止状态为一个轻量搜索图标，点击后向两侧延展并弹出快捷推荐标签。",
    tags: ["Search", "Morphing", "Input"],
    componentKey: "beui-morphing-search-demo",
  },
  {
    id: "beui-notification-stack",
    name: "Notification Stack Drawer",
    nameCn: "多源通知聚合与折叠收纳抽屉",
    category: "block",
    siteId: "beui",
    siteName: "beui.dev",
    siteUrl: "https://beui.dev",
    originUrl: "https://beui.dev/components/blocks/notification-stack",
    status: "collected",
    description: "将来自 Slack、GitHub、系统邮件的多条警报折叠为整洁卡片，支持一键清空。",
    tags: ["Notification", "Stack", "Drawer"],
    componentKey: "beui-notification-stack-demo",
  },
  {
    id: "beui-availability-scheduler",
    name: "Availability Scheduler Matrix",
    nameCn: "每周空闲会议档期滑动预约器",
    category: "block",
    siteId: "beui",
    siteName: "beui.dev",
    siteUrl: "https://beui.dev",
    originUrl: "https://beui.dev/components/blocks/availability-scheduler",
    status: "collected",
    description: "支持框选周一至周五的可用时间段，自动识别时区冲突并生成预约日历。",
    tags: ["Scheduler", "Calendar", "Booking"],
    componentKey: "beui-scheduler-demo",
  },
  {
    id: "beui-project-folder",
    name: "Project Folder Skeuomorphic Binder",
    nameCn: "拟物化项目文件折叠夹与标签卡",
    category: "block",
    siteId: "beui",
    siteName: "beui.dev",
    siteUrl: "https://beui.dev",
    originUrl: "https://beui.dev/components/blocks/project-folder",
    status: "collected",
    description: "双层文件夹视觉，点击文件夹标签即可上浮出内部包含的设计稿与文档列表。",
    tags: ["Folder", "Design", "Block"],
    componentKey: "beui-project-folder-demo",
  },
  {
    id: "beui-otp-input",
    name: "OTP Input Segmented Security Code",
    nameCn: "6格独立聚焦一次性安全验证码",
    category: "block",
    siteId: "beui",
    siteName: "beui.dev",
    siteUrl: "https://beui.dev",
    originUrl: "https://beui.dev/components/blocks/otp-input",
    status: "collected",
    description: "自动跳转下一格、支持粘贴完整串自动分段分配，并配有校验通过动效。",
    tags: ["OTP", "Security", "Input"],
    componentKey: "beui-otp-demo",
  },
  {
    id: "beui-feedback-widget",
    name: "Feedback Widget Mood & Comment Box",
    nameCn: "表情心情评分与轻量反馈悬浮挂件",
    category: "block",
    siteId: "beui",
    siteName: "beui.dev",
    siteUrl: "https://beui.dev",
    originUrl: "https://beui.dev/components/blocks/feedback-widget",
    status: "collected",
    description: "集成 5 档生动 Emoji 表情选择与单行意见提交，完成后展示感谢动效。",
    tags: ["Feedback", "Widget", "Rating"],
    componentKey: "beui-feedback-demo",
  },

  // --- Agents Components ---
  {
    id: "beui-voice-orb",
    name: "Voice Orb Real-time Audio Visualizer",
    nameCn: "AI 实时语音交谈波形流动能量球",
    category: "component",
    siteId: "beui",
    siteName: "beui.dev",
    siteUrl: "https://beui.dev",
    originUrl: "https://beui.dev/components/agents/voice-orb",
    status: "collected",
    description: "仿 Siri / Gemini Live 的多层彩色流体能量球，随麦克风音量动态波荡起伏。",
    tags: ["VoiceOrb", "AI", "Audio"],
    componentKey: "beui-voice-orb-demo",
  },
  {
    id: "beui-agent-approval-card",
    name: "Tool Approval Human-in-the-Loop Card",
    nameCn: "智能体高危工具调用人工审批卡",
    category: "block",
    siteId: "beui",
    siteName: "beui.dev",
    siteUrl: "https://beui.dev",
    originUrl: "https://beui.dev/components/agents/approval-card",
    status: "collected",
    description: "展示 Agent 计划调用的 Bash 命令行与文件修改 Diff，由工程师授权或驳回。",
    tags: ["Agent", "Approval", "HITL"],
    componentKey: "beui-approval-demo",
  },
];

console.log(`Prepared ${BEUI_ITEMS.length} new beui.dev components/blocks.`);

let registryCode = fs.readFileSync("./src/data/components-registry.ts", "utf-8");

const existingIds = new Set([...registryCode.matchAll(/id:\s*"([^"]+)"/g)].map(m => m[1]));
const itemsToAdd = BEUI_ITEMS.filter(item => !existingIds.has(item.id));

console.log(`Adding ${itemsToAdd.length} non-duplicate beui items to components-registry.ts`);

const formattedItems = itemsToAdd.map(item => {
  return `  {
    id: ${JSON.stringify(item.id)},
    name: ${JSON.stringify(item.name)},
    nameCn: ${JSON.stringify(item.nameCn)},
    category: ${JSON.stringify(item.category)},
    siteId: ${JSON.stringify(item.siteId)},
    siteName: ${JSON.stringify(item.siteName)},
    siteUrl: ${JSON.stringify(item.siteUrl)},
    originUrl: ${JSON.stringify(item.originUrl)},
    status: ${JSON.stringify(item.status)},
    description: ${JSON.stringify(item.description)},
    tags: ${JSON.stringify(item.tags)},
    componentKey: ${JSON.stringify(item.componentKey)},
  },`;
}).join("\n");

const closingIndex = registryCode.lastIndexOf("];");
if (closingIndex !== -1) {
  registryCode = registryCode.slice(0, closingIndex) + formattedItems + "\n];\n";
  fs.writeFileSync("./src/data/components-registry.ts", registryCode, "utf-8");
  console.log("Successfully appended beui.dev items to components-registry.ts!");
} else {
  console.error("Could not find closing of REGISTRY_DATA");
}
